alias cat='bat --paging=never'
alias ls='lsd -a'
alias e='explorer'
alias restart='shutdown /r /t 0'
alias poweroff='shutdown /s /t 0'
alias ed='nano ~/.bashrc'
alias ged='zed ~/.bashrc'
alias resh='exec bash'
alias find='fd'
alias grep='rg'
